version: '3'
services:
  minio:
    image: "minio/minio:latest"
    command: ["minio", "server", "/mnt/minio_data"]
    ports:
      - "9001:9000"
    restart: on-failure
    env_file: settings.env
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniostorage
      - MINIO_BROWSER=off
    volumes:
      - "/tmp/minio_internal:/mnt/minio_data"
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 80M
        reservations:
          cpus: '0.05'
          memory: 30M
  gpg_worker:
    build: .
    restart: on-failure
    env_file: settings.env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 80M
        reservations:
          memory: 30M
